<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Overview extends CI_Model{

	function get_numbers(){

		//Get all active campaigns
		$query = $this->db->query("Select campaignid from vtiger_campaign INNER JOIN vtiger_crmentity on (vtiger_crmentity.crmid = vtiger_campaign.campaignid) where deleted=0 and campaignname not like '%self%'")->result();
		foreach($query as $row){
			$active_campaigns[] = $row->campaignid;
		}

		$data = array(
			//donut chart
			'active_leads' => $this->db->query("Select * from vtiger_leaddetails INNER JOIN vtiger_crmentity on (vtiger_crmentity.crmid=vtiger_leaddetails.leadid) where deleted=0 and converted=0 and date(modifiedtime)>=date(date(now())-14) and modifiedtime!=createdtime"),
			'inactive' => $this->db->query("Select * from vtiger_leaddetails INNER JOIN vtiger_crmentity on (vtiger_crmentity.crmid=vtiger_leaddetails.leadid) where deleted=0 and converted=0 and date(modifiedtime)<date(date(now())-14) and modifiedtime!=createdtime"),
			'never_updated' => $this->db->query("Select * from vtiger_leaddetails INNER JOIN vtiger_crmentity on (vtiger_crmentity.crmid=vtiger_leaddetails.leadid) where deleted=0 and converted=0 and modifiedtime=createdtime"),

			//campaign leads
			'unassigned' => $this->db->query("SELECT company,concat(firstname,' ',lastname) as name,phone,email,concat(vtiger_users.first_name,' ',vtiger_users.last_name) as assigned_to FROM vtiger_leaddetails INNER JOIN vtiger_leadscf on (vtiger_leaddetails.leadid = vtiger_leadscf.leadid) INNER JOIN vtiger_campaignleadrel ON vtiger_campaignleadrel.leadid=vtiger_leaddetails.leadid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadsubdetails  ON vtiger_leadsubdetails.leadsubscriptionid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadaddress ON vtiger_leadaddress.leadaddressid = vtiger_leadsubdetails.leadsubscriptionid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignleadrel.campaignrelstatusid WHERE vtiger_crmentity.deleted=0 and vtiger_users.first_name='' and campaignid in (" . implode(',',$active_campaigns) . ") group by vtiger_leaddetails.leadid"),
			'assigned' => $this->db->query("SELECT company,concat(firstname,' ',lastname) as name,phone,email,concat(vtiger_users.first_name,' ',vtiger_users.last_name) as assigned_to FROM vtiger_leaddetails INNER JOIN vtiger_leadscf on (vtiger_leaddetails.leadid = vtiger_leadscf.leadid) INNER JOIN vtiger_campaignleadrel ON vtiger_campaignleadrel.leadid=vtiger_leaddetails.leadid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadsubdetails  ON vtiger_leadsubdetails.leadsubscriptionid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadaddress ON vtiger_leadaddress.leadaddressid = vtiger_leadsubdetails.leadsubscriptionid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignleadrel.campaignrelstatusid WHERE vtiger_crmentity.deleted=0 and vtiger_users.first_name!='' and campaignid in (" . implode(',',$active_campaigns) . ") group by vtiger_leaddetails.leadid"),
			'c_active' => $this->db->query("SELECT company,concat(firstname,' ',lastname) as name,phone,email,concat(vtiger_users.first_name,' ',vtiger_users.last_name) as assigned_to FROM vtiger_leaddetails INNER JOIN vtiger_leadscf on (vtiger_leaddetails.leadid = vtiger_leadscf.leadid) INNER JOIN vtiger_campaignleadrel ON vtiger_campaignleadrel.leadid=vtiger_leaddetails.leadid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadsubdetails  ON vtiger_leadsubdetails.leadsubscriptionid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadaddress ON vtiger_leadaddress.leadaddressid = vtiger_leadsubdetails.leadsubscriptionid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignleadrel.campaignrelstatusid WHERE vtiger_crmentity.deleted=0 and campaignid in (" . implode(',',$active_campaigns) . ") and date(modifiedtime)>=date(date(now())-14) group by vtiger_leaddetails.leadid"),
			'c_inactive' => $this->db->query("SELECT company,concat(firstname,' ',lastname) as name,phone,email,concat(vtiger_users.first_name,' ',vtiger_users.last_name) as assigned_to FROM vtiger_leaddetails INNER JOIN vtiger_leadscf on (vtiger_leaddetails.leadid = vtiger_leadscf.leadid) INNER JOIN vtiger_campaignleadrel ON vtiger_campaignleadrel.leadid=vtiger_leaddetails.leadid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadsubdetails  ON vtiger_leadsubdetails.leadsubscriptionid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadaddress ON vtiger_leadaddress.leadaddressid = vtiger_leadsubdetails.leadsubscriptionid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignleadrel.campaignrelstatusid WHERE vtiger_crmentity.deleted=0 and campaignid in (" . implode(',',$active_campaigns) . ") and date(modifiedtime)<date(date(now())-14) and modifiedtime!=createdtime group by vtiger_leaddetails.leadid"),
			'c_never_updated' => $this->db->query("SELECT company,concat(firstname,' ',lastname) as name,phone,email,concat(vtiger_users.first_name,' ',vtiger_users.last_name) as assigned_to FROM vtiger_leaddetails INNER JOIN vtiger_leadscf on (vtiger_leaddetails.leadid = vtiger_leadscf.leadid) INNER JOIN vtiger_campaignleadrel ON vtiger_campaignleadrel.leadid=vtiger_leaddetails.leadid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadsubdetails  ON vtiger_leadsubdetails.leadsubscriptionid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadaddress ON vtiger_leadaddress.leadaddressid = vtiger_leadsubdetails.leadsubscriptionid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignleadrel.campaignrelstatusid WHERE vtiger_crmentity.deleted=0 and campaignid in (" . implode(',',$active_campaigns) . ") and modifiedtime=createdtime group by vtiger_leaddetails.leadid"),
			'by_industry' => $this->db->query("SELECT DISTINCT vtiger_leaddetails.leadid, cf_758, count(cf_758) as count FROM vtiger_leaddetails INNER JOIN vtiger_campaignleadrel ON vtiger_campaignleadrel.leadid=vtiger_leaddetails.leadid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadsubdetails ON vtiger_leadsubdetails.leadsubscriptionid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadaddress ON vtiger_leadaddress.leadaddressid = vtiger_leadsubdetails.leadsubscriptionid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignleadrel.campaignrelstatusid INNER JOIN vtiger_leadscf on (vtiger_leadscf.leadid = vtiger_leaddetails.leadid) WHERE vtiger_crmentity.deleted=0 and campaignid in (" . implode(',',$active_campaigns) . ") GROUP BY cf_758"),
			'by_rating' => $this->db->query("SELECT DISTINCT vtiger_leaddetails.leadid, rating, count(rating) as count FROM vtiger_leaddetails INNER JOIN vtiger_campaignleadrel ON vtiger_campaignleadrel.leadid=vtiger_leaddetails.leadid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadsubdetails  ON vtiger_leadsubdetails.leadsubscriptionid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadaddress ON vtiger_leadaddress.leadaddressid = vtiger_leadsubdetails.leadsubscriptionid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignleadrel.campaignrelstatusid WHERE vtiger_crmentity.deleted=0 and campaignid in (" . implode(',',$active_campaigns) . ") group by rating"),

			//campaign accounts
			'new_this_year' => $this->db->query("SELECT accountname,cf_754, bill_street, cf_754 as industry, concat(first_name,' ',last_name) as name FROM vtiger_account INNER JOIN vtiger_accountscf on (vtiger_account.accountid=vtiger_accountscf.accountid) INNER JOIN vtiger_accountbillads on (vtiger_account.accountid=vtiger_accountbillads.accountaddressid) INNER JOIN vtiger_campaignaccountrel ON vtiger_campaignaccountrel.accountid = vtiger_account.accountid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_account.accountid INNER JOIN vtiger_users on (vtiger_users.id=vtiger_crmentity.smownerid) LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignaccountrel.campaignrelstatusid WHERE vtiger_crmentity.deleted =0 and campaignid in (" . implode(',',$active_campaigns) . ") and YEAR(createdtime)=YEAR(now()) order by smownerid"),
			'warm_accounts' => $this->db->query("SELECT accountname,cf_754, bill_street, cf_754 as industry, concat(first_name,' ',last_name) as name FROM vtiger_account INNER JOIN vtiger_accountscf on (vtiger_account.accountid=vtiger_accountscf.accountid) INNER JOIN vtiger_accountbillads on (vtiger_account.accountid=vtiger_accountbillads.accountaddressid) INNER JOIN vtiger_campaignaccountrel ON vtiger_campaignaccountrel.accountid = vtiger_account.accountid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_account.accountid INNER JOIN vtiger_users on (vtiger_users.id=vtiger_crmentity.smownerid) LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignaccountrel.campaignrelstatusid WHERE vtiger_crmentity.deleted =0 and campaignid in (" . implode(',',$active_campaigns) . ") and date(modifiedtime)>=date(date(now())-14) order by smownerid"),
			'cold_accounts' => $this->db->query("SELECT accountname,cf_754, bill_street, cf_754 as industry, concat(first_name,' ',last_name) as name FROM vtiger_account INNER JOIN vtiger_accountscf on (vtiger_account.accountid=vtiger_accountscf.accountid) INNER JOIN vtiger_accountbillads on (vtiger_account.accountid=vtiger_accountbillads.accountaddressid) INNER JOIN vtiger_campaignaccountrel ON vtiger_campaignaccountrel.accountid = vtiger_account.accountid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_account.accountid INNER JOIN vtiger_users on (vtiger_users.id=vtiger_crmentity.smownerid) LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignaccountrel.campaignrelstatusid WHERE vtiger_crmentity.deleted =0 and campaignid in (" . implode(',',$active_campaigns) . ") and date(modifiedtime)<date(date(now())-14) order by smownerid"),
			'assigned_accounts' => $this->db->query("SELECT accountname,cf_754, bill_street, cf_754 as industry, concat(first_name,' ',last_name) as name FROM vtiger_account INNER JOIN vtiger_accountscf on (vtiger_account.accountid=vtiger_accountscf.accountid) INNER JOIN vtiger_accountbillads on (vtiger_account.accountid=vtiger_accountbillads.accountaddressid) INNER JOIN vtiger_campaignaccountrel ON vtiger_campaignaccountrel.accountid = vtiger_account.accountid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_account.accountid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignaccountrel.campaignrelstatusid WHERE vtiger_crmentity.deleted =0 and campaignid in (" . implode(',',$active_campaigns) . ") and first_name != '' order by smownerid"),
			'unassigned_accounts' => $this->db->query("SELECT accountname,cf_754, bill_street, cf_754 as industry, concat(first_name,' ',last_name) as name FROM vtiger_account INNER JOIN vtiger_accountscf on (vtiger_account.accountid=vtiger_accountscf.accountid) INNER JOIN vtiger_accountbillads on (vtiger_account.accountid=vtiger_accountbillads.accountaddressid) INNER JOIN vtiger_campaignaccountrel ON vtiger_campaignaccountrel.accountid = vtiger_account.accountid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_account.accountid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignaccountrel.campaignrelstatusid WHERE vtiger_crmentity.deleted =0 and campaignid in (" . implode(',',$active_campaigns) . ") and first_name = '' order by smownerid"),
		
			'campaign_leads' => $this->db->query("SELECT vtiger_leaddetails.*, vtiger_crmentity.crmid,vtiger_leadaddress.phone,vtiger_leadsubdetails.website, vtiger_crmentity.smownerid, vtiger_campaignrelstatus.* FROM vtiger_leaddetails INNER JOIN vtiger_campaignleadrel ON vtiger_campaignleadrel.leadid=vtiger_leaddetails.leadid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadsubdetails  ON vtiger_leadsubdetails.leadsubscriptionid = vtiger_leaddetails.leadid INNER JOIN vtiger_leadaddress ON vtiger_leadaddress.leadaddressid = vtiger_leadsubdetails.leadsubscriptionid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignleadrel.campaignrelstatusid WHERE vtiger_crmentity.deleted=0 and campaignid in (" . implode(',',$active_campaigns) . ") group by vtiger_leaddetails.leadid"),
			'campaign_accounts' => $this->db->query("SELECT vtiger_account . * , vtiger_crmentity . * , vtiger_crmentity.modifiedtime, vtiger_campaignrelstatus . * FROM vtiger_account INNER JOIN vtiger_campaignaccountrel ON vtiger_campaignaccountrel.accountid = vtiger_account.accountid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_account.accountid LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaignaccountrel.campaignrelstatusid WHERE vtiger_crmentity.deleted =0 and campaignid in (" . implode(',',$active_campaigns) . ") order by vtiger_account.accountid"),
			'campaign_contacts' => $this->db->query("SELECT vtiger_contactdetails.accountid, vtiger_account.accountname, vtiger_contactdetails.contactid, vtiger_contactdetails.lastname, vtiger_contactdetails.firstname, vtiger_contactdetails.title, vtiger_contactdetails.department, vtiger_contactdetails.email, vtiger_contactdetails.phone, vtiger_crmentity.crmid, vtiger_crmentity.smownerid, vtiger_crmentity.modifiedtime, vtiger_campaignrelstatus.* FROM vtiger_contactdetails INNER JOIN vtiger_campaigncontrel ON vtiger_campaigncontrel.contactid = vtiger_contactdetails.contactid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_contactdetails.contactid LEFT JOIN vtiger_groups ON vtiger_groups.groupid=vtiger_crmentity.smownerid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid=vtiger_users.id LEFT JOIN vtiger_account ON vtiger_account.accountid = vtiger_contactdetails.accountid LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaigncontrel.campaignrelstatusid WHERE vtiger_campaigncontrel.campaignid in (" . implode(',',$active_campaigns) . ") AND vtiger_crmentity.deleted=0"),
			'campaign_opportunities' => $this->db->query("SELECT vtiger_potential.related_to, vtiger_account.accountname, vtiger_potential.potentialid, vtiger_potential.potentialname, vtiger_potential.potentialtype, vtiger_potential.sales_stage, vtiger_potential.amount, vtiger_potential.closingdate, vtiger_crmentity.crmid, vtiger_crmentity.smownerid FROM vtiger_campaign INNER JOIN vtiger_potential ON vtiger_campaign.campaignid = vtiger_potential.campaignid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_potential.potentialid LEFT JOIN vtiger_groups ON vtiger_groups.groupid=vtiger_crmentity.smownerid LEFT JOIN vtiger_users ON vtiger_users.id=vtiger_crmentity.smownerid LEFT JOIN vtiger_account ON vtiger_account.accountid = vtiger_potential.related_to WHERE vtiger_crmentity.deleted=0 and vtiger_campaign.campaignid in (" . implode(',',$active_campaigns) . ")"),
			
			//campaign contacts
			'contact_this_year' => $this->db->query("SELECT vtiger_contactdetails.accountid, vtiger_account.accountname, vtiger_contactdetails.contactid, vtiger_contactdetails.lastname, vtiger_contactdetails.firstname, vtiger_contactdetails.title, vtiger_contactdetails.department, vtiger_contactdetails.email, vtiger_contactdetails.phone, vtiger_crmentity.crmid, vtiger_crmentity.smownerid, vtiger_crmentity.modifiedtime, vtiger_campaignrelstatus.* FROM vtiger_contactdetails INNER JOIN vtiger_campaigncontrel ON vtiger_campaigncontrel.contactid = vtiger_contactdetails.contactid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_contactdetails.contactid LEFT JOIN vtiger_groups ON vtiger_groups.groupid=vtiger_crmentity.smownerid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid=vtiger_users.id LEFT JOIN vtiger_account ON vtiger_account.accountid = vtiger_contactdetails.accountid LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaigncontrel.campaignrelstatusid WHERE vtiger_campaigncontrel.campaignid in (" . implode(',',$active_campaigns) . ") AND vtiger_crmentity.deleted=0 and YEAR(createdtime) = YEAR(now())"),
			//'c_contact_aec' => $this->db->query("SELECT vtiger_contactdetails.accountid, vtiger_account.accountname, vtiger_contactdetails.contactid, vtiger_contactdetails.lastname, vtiger_contactdetails.firstname, vtiger_contactdetails.title, vtiger_contactdetails.department, vtiger_contactdetails.email, vtiger_contactdetails.phone, vtiger_crmentity.crmid, vtiger_crmentity.smownerid, vtiger_crmentity.modifiedtime, vtiger_campaignrelstatus.* FROM vtiger_contactdetails INNER JOIN vtiger_campaigncontrel ON vtiger_campaigncontrel.contactid = vtiger_contactdetails.contactid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_contactdetails.contactid LEFT JOIN vtiger_groups ON vtiger_groups.groupid=vtiger_crmentity.smownerid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid=vtiger_users.id LEFT JOIN vtiger_account ON vtiger_account.accountid = vtiger_contactdetails.accountid LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaigncontrel.campaignrelstatusid WHERE vtiger_campaigncontrel.campaignid in (" . implode(',',$active_campaigns) . ") AND vtiger_crmentity.deleted=0"),
			//'c_contact_manufacturing' => $this->db->query("SELECT vtiger_contactdetails.accountid, vtiger_account.accountname, vtiger_contactdetails.contactid, vtiger_contactdetails.lastname, vtiger_contactdetails.firstname, vtiger_contactdetails.title, vtiger_contactdetails.department, vtiger_contactdetails.email, vtiger_contactdetails.phone, vtiger_crmentity.crmid, vtiger_crmentity.smownerid, vtiger_crmentity.modifiedtime, vtiger_campaignrelstatus.* FROM vtiger_contactdetails INNER JOIN vtiger_campaigncontrel ON vtiger_campaigncontrel.contactid = vtiger_contactdetails.contactid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_contactdetails.contactid LEFT JOIN vtiger_groups ON vtiger_groups.groupid=vtiger_crmentity.smownerid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid=vtiger_users.id LEFT JOIN vtiger_account ON vtiger_account.accountid = vtiger_contactdetails.accountid LEFT JOIN vtiger_campaignrelstatus ON vtiger_campaignrelstatus.campaignrelstatusid = vtiger_campaigncontrel.campaignrelstatusid WHERE vtiger_campaigncontrel.campaignid in (" . implode(',',$active_campaigns) . ") AND vtiger_crmentity.deleted=0"),

			//campaign oppotunities
			'opportunities_by_stage' => $this->db->query("SELECT sales_stage, count(sales_stage) as count, sum(amount) as amount FROM vtiger_campaign INNER JOIN vtiger_potential ON vtiger_campaign.campaignid = vtiger_potential.campaignid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_potential.potentialid LEFT JOIN vtiger_groups ON vtiger_groups.groupid=vtiger_crmentity.smownerid LEFT JOIN vtiger_users ON vtiger_users.id=vtiger_crmentity.smownerid LEFT JOIN vtiger_account ON vtiger_account.accountid = vtiger_potential.related_to WHERE vtiger_crmentity.deleted=0 and vtiger_campaign.campaignid in (" . implode(',',$active_campaigns) . ") GROUP BY sales_stage"),
			
			'top_active' => $this->db->query("SELECT CONCAT( first_name,  ' ', last_name ) AS name, COUNT( * ) AS activity FROM vtiger_crmentity INNER JOIN vtiger_users ON vtiger_users.id = vtiger_crmentity.modifiedby WHERE vtiger_users.status =  'active' AND id !=1 AND WEEKOFYEAR( modifiedtime ) = WEEKOFYEAR( NOW( ) ) AND YEAR( modifiedtime ) = YEAR( NOW( ) ) GROUP BY modifiedby ORDER BY COUNT( * ) DESC LIMIT 0 , 5")->result(),
		);

		return $data;	
	}

	function get_overall_chart($duration){
		$timeline = array(
			'1W' => 'DATE_SUB(date(now()), INTERVAL 1 WEEK)',
			'2W' => 'DATE_SUB(date(now()), INTERVAL 2 WEEK)',
			'M' => 'DATE_SUB(date(now()), INTERVAL 1 MONTH)',
			'Y' => 'DATE_SUB(date(now()), INTERVAL 1 YEAR)',
			);		

		$data = array(
			'active_leads' => $this->db->query("Select * from vtiger_leaddetails INNER JOIN vtiger_crmentity on (vtiger_crmentity.crmid=vtiger_leaddetails.leadid) where deleted=0 and converted=0 and date(modifiedtime)>=" . $timeline[$duration] . " and modifiedtime!=createdtime")->num_rows(),
			'inactive' => $this->db->query("Select * from vtiger_leaddetails INNER JOIN vtiger_crmentity on (vtiger_crmentity.crmid=vtiger_leaddetails.leadid) where deleted=0 and converted=0 and date(modifiedtime)<" . $timeline[$duration] . " and modifiedtime!=createdtime")->num_rows(),
			'never_updated' => $this->db->query("Select * from vtiger_leaddetails INNER JOIN vtiger_crmentity on (vtiger_crmentity.crmid=vtiger_leaddetails.leadid) where deleted=0 and converted=0 and modifiedtime=createdtime")->num_rows(),
			);
		return $data;
	}
}